### PR TITLE
Async Database and real transcations

### PR DESCRIPTION
**Pull request by Maan2003**

### CODE REVIEW

**Comment by Maan2003** [comment]
This is ready for review for types and definitions. 

I have not migrated the codebase yet. It is better to do after definitions are finalized to avoid redoing the work again and again.

**Comment by Maan2003** [comment]
This is also blocked on #25. sled's [`transaction`](https://docs.rs/sled/latest/sled/struct.Tree.html#method.transaction) is very restrictive for lifetimes and async

**Comment by elsirion** [comment]
How does this interact with #173? What would be your proposed strategy? Just make it part of the PR series that will resolve #25 or keep it open as a separate one? I saw you were active in that PR.

**Comment by elsirion** [comment]
Ok, then let's close it for now :)

**Pull request closed without merging**
