### PR TITLE
Dynamic Module experiment

### PR DESCRIPTION
**Pull request by Maan2003**
another take on #144 using erased type pattern from `erased-serde` 

it was just easier to explain with code

### CODE REVIEW

**Comment by elsirion** [comment]
I wonder how you deal with deserialization errors. Right now these happen early on when e.g. federation members can be blamed for submitting faulty consensus items (that would actually happen inside HBBFT and we don't have to care at all right now). With this approach that could happen way later when we don't even know anymore which member contributed the faulty data element. 

I'm personally more a fan of a mix of macros and type system hacks [like this](https://gist.github.com/elsirion/009068463a01494f4be6da5cb0211860#file-legofed-rs-L195-L204) by now, together they can probably lead to something usable. Also ugly but at least keeps the guarantees static typing gives us.

2022-07-07-211301_3840x2160_scrot

**Comment by Maan2003** [comment]
[`typetag`](https://github.com/dtolnay/typetag) can help to deserialize to one of the possible `Input`s or fail fast.

**Comment by Maan2003** [comment]
macros and/or generics hack are much better solution here :smile:

**Comment by elsirion** [comment]
Idk yet, still need to figure it out tbh, but I have a feeling that it'd avoid many pitfalls.

**Pull request closed without merging**
