### PR TITLE
Updating the links to rust-secp256k1-zkp repo

### PR DESCRIPTION
**Pull request by wiredhikari**
This might help fix some errors in nix-builds

### CODE REVIEW

**Comment by elsirion** [comment]
Since this is a step towards #90, would you mind adding a commit that adds testing `default.nix` back to CI? I think it perfectly fits one PR and would make this change testable (before: `nix-build` fails, after it succeeds).

**Comment by elsirion** [comment]
Can you squash the commits please? Both update the `Cargo.lock` file.

**Comment by elsirion** [comment]
> Since this is a step towards https://github.com/fedimint/minimint/issues/90, would you mind adding a commit that adds testing default.nix back to CI?

**Comment by wiredhikari** [comment]
> > Since this is a step towards https://github.com/fedimint/minimint/issues/90, would you mind adding a commit that adds testing default.nix back to CI?

It has been added in pr #111

**Comment by elsirion** [comment]
Ah, sorry, didn't notice

**Comment by elsirion** [comment]
Ah, sorry, didn't notice

**Pull request merged**
