### PR TITLE
revert buildjet (trying to get ci to run)

### PR DESCRIPTION
**Pull request by justinmoon**

### CODE REVIEW

**Comment by justinmoon** [comment]
@elsirion it seems that buildjet runners are stuck right now. If anyone needs CI to run until this is fixed, feel free to cherry-pick this commit temporarily.

**Comment by justinmoon** [comment]
seems like the problem went away

**Comment by elsirion** [comment]
I reached out to them about this.

**Comment by elsirion** [comment]
They got back to me and pointed to [this document](https://buildjet.com/for-github-actions/docs/runners#concurrent-runners).

> Every BuildJet for GitHub Actions account start with ability to run 64 concurrent AMD64 vCPU's and 32 concurrent ARM vCPU's, which is the upper limit of vCPU's you can have active in parallel.

They offered the following:

> We sell Concurrency Extensions, where you get an additional 100vCPU's to your budget for $250/month.
> This would give you the ability to run 164 vCPU's in parallel and should significantly reduce the waiting time for your tasks.

Maybe we can try to reduce CPU counts for some tasks first, I don't really feel like paying that much.

**Comment by jkitman** [comment]
> Maybe we can try to reduce CPU counts for some tasks first

I think the pattern of creating a new GH action for every shell script we want to run is not ideal.  Most of the time is spent building and setting up the federation, not in actual testing.  We could probably combine them together and ideally move from bash to Rust for some of them.

**Comment by dpc** [comment]
I think there's plenty of room for improvement in the way the CI is set up RN, and test are ran done and other things, etc.

Also while working on the flake-based CI, I cranked a lot of builds before I was able to get things to work.

But I also wan to point out that $250/mo is not a lot of money if it might save each contributor a minute or two in every other PR.(I don't know if it will, but we can evaluate once things are more optimally set-up). Time is sats.

**Comment by justinmoon** [comment]
This is happening again. Messaged them again. It's not just the concurrency limit because right now nothing is running and jobs are stuck. They are looking into the issue now.

**Pull request closed without merging**
