### PR TITLE
client: make requests to federation members concurrent

### PR DESCRIPTION
**Pull request by Maan2003**

### CODE REVIEW

**Comment by justinmoon** [comment]
This looks like a great improvement.

I think currently the API calls do happen concurrently, but we just force them to arrive in order of peer ID. 

So if all HTTP requests take, say, 100ms then it isn't a problem. But if we have 4 servers and requests to nodes 1-3 take 10ms and the request to node 0 takes 100 ms, then we waste 90 ms because waiting for response from server 0 when we could just accept the responses from servers 1-3.

Also, I wonder if this change is revealing some kind of bad assumption somewhere: https://github.com/fedimint/minimint/runs/7184767177?check_suite_focus=true#step:5:4032. That failure doesn't happen locally for me. 

Locally I saw the following error:

```
failures:

---- receive_lightning_payment_invalid_preimage stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FinalizationError(UnknownIssuance)', integrationtests/tests/fixtures/mod.rs:412:45
thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:259:41
thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:259:41

---- receive_lightning_payment_valid_preimage stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FinalizationError(UnknownIssuance)', integrationtests/tests/fixtures/mod.rs:412:45
thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:259:41


failures:
    receive_lightning_payment_invalid_preimage
    **receive_lightning_payment_valid_preimage**
```

But then re-ran the tests and they succeeded.

**Comment by justinmoon** [comment]
Also, I noticed that `ERROR tide::listener::tcp_listener: async-h1 error` log statements started showing up. This is probably because we are now closing HTTP connections before they succeed once we have enough responses from other servers.

**Comment by justinmoon** [comment]
> No, futures only start when polled and stream::iter only polls next future after current future is completed.

Ahh looks like I'm wrong!

**Comment by elsirion** [comment]
> Locally I saw the following error:
> ```
> …
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FinalizationError(UnknownIssuance)', integrationtests/tests/fixtures/mod.rs:412:45
> …
> ```

Notably that's another error than we are getting in CI, are you sure it's not caused by something else @justinmoon?

The one we are getting in CI right now is

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FinalizationError(WrongMintAnswer)', integrationtests/tests/fixtures/mod.rs:313:45
```

which seems much more likely to be related to this PR. E.g. there will always be one mint that doesn't know about newly issued e-cash tokens yet (see #198), so that might be seen as a wrong mint answer?

**Comment by elsirion** [comment]
Any updates here? Did we find the bug? Will this change be part of #203?

**Comment by Maan2003** [comment]
I think bug is not caused by this PR, this just makes the bug more likely.

> Will this change be part of #203?

No completely, that makes requests concurrent but not unordered. So we still wait for first peer if it is slow.

**Comment by Maan2003** [comment]
(updated for web sockets)

**Review by elsirion — APPROVED** [review]

**Pull request merged**
