### PR TITLE
Jäger!

### PR DESCRIPTION
**Pull request by Maan2003**

### CODE REVIEW

**Comment by elsirion** [comment]
I feel like we should make telemetry reporting a command line flag. It's useful for testing but a potential security risk for deployments. We depend on structopt already, maybe use that? Although I remember someone telling me clap had derive features too now, so maybe use that instead.

**Comment by NicolaLS** [comment]
> I feel like we should make telemetry reporting a command line flag. It's useful for testing but a potential security risk for deployments. We depend on structopt already, maybe use that? Although I remember someone telling me clap had derive features too now, so maybe use that instead.

Yes I think it'd be good to use clap:
"As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added"
from: https://docs.rs/structopt/latest/structopt/

**Comment by Maan2003** [comment]
I suggest using a feature flag. We can make opentelementry deps optional then.

**Comment by elsirion** [comment]
I'm really excited about this, currently trying to get it to run! But I had to dig quite a bit to find how to get started, maybe you could add some documentation about:

* Which ports are used to communicate and in which direction, does it use encryption etc. This will be useful for test deployments that might communicate over the open internet.
* How to get the UI to work (probably just linking to https://docs.rs/opentelemetry-jaeger/0.16.0/opentelemetry_jaeger/#quickstart)

**Review by elsirion — APPROVED** [review]
Really cool addition, we just need to use spans more and this will be a great debug tool!

**Pull request merged**
